### PR TITLE
[#2] Implemented extraction of log credentials.

### PR DESCRIPTION
**Pull request by tamerharsh**

### CODE REVIEW

**Comment by inbangsa** [comment]
Please give me the reason  why this should be your first pull request.. 

We already discussed to take bottom to top approch 

First define your formatter class interface

Then define a class which uses formatter class to format log messages and writes the log to any sink( file, database, web) 

Then we define logger class interface which takes sink object and logs the user log messages throught that sink.

**Comment by tamerharsh** [comment]
> Why static function ?
 To be used in macro ,hence thought of not using with object.

> Doxygen style comments only please.
yes

**Comment by tamerharsh** [comment]
> Doxygen style comments only please

ok.

**Comment by tamerharsh** [comment]
closing this PR  as this is not required for the first commit .

**Pull request closed without merging**
